### ISSUE TITLE
Connection issues to CX8090 (Twincat2)

### ISSUE THREAD

**Issue by RikMe** [jisotalo/node-red-contrib-ads-client#19]
PLC: 192.168.11.3
AMSnetID PLC: 5.50.37.33.1.1
Twincat 2

Raspberry Pi : 192.168.11.2

Route has been created on PLC. Settings should be according tot tutorials

Error : "Failed to connect 5.50.37.33.1.1:801 at startup: ClientException: Connection failed: Device system manager state read failed - ADS error -1 (Timeout - no response in 6000 ms)"

![image](https://user-images.githubusercontent.com/44720237/197229022-911db890-c5d1-4a5c-a493-378b78625e62.png)
![image](https://user-images.githubusercontent.com/44720237/197228928-b9b14c95-8b38-4f6f-92ea-59b5102cf51f.png)
![image](https://user-images.githubusercontent.com/44720237/197229276-fc17a17e-481d-4f1a-b452-b4da08723252.png)

**Comment by jisotalo** [comment]
Closing this. Please don't make multiple issues at the same time.

https://github.com/jisotalo/ads-client/issues/99
