### ISSUE TITLE
Real number in PLC but INT in node-red

### ISSUE THREAD

**Issue by offrok** [jisotalo/node-red-contrib-ads-client#21]
I declared the subscribed variable as a REAL output variable in TwinCAT 3. When i read it with the subscribe node i only get an INT value (without the decimal places) when i use the debug node.

**Comment by jisotalo** [comment]
Hi!

Most probably the REAL variable has that kind of value that decimals are 0? I think Javascript won't show decimal numbers if they are all zeros (in all cases, depends on usage).

Test with number like 123.123

**Comment by offrok** [comment]
Thank you for your answer but that doesn´t seem to be the Problem, since those are fast changing temperature values that have many different decimals

**Comment by jisotalo** [comment]
Could you please share some data. This isn't really helping.

**Comment by offrok** [comment]
I have just looked over the PLC program again. The problem seems to be inside my PLC program. The values also show no decimals even though they are declared as a real datatype and according to the calculation they also should have decimals. In other programs i have also noticed that your library works with reals.

**Comment by jisotalo** [comment]
Thanks for reporting that!
