### ISSUE TITLE
subscribe multiple

### ISSUE THREAD

**Issue by vdwpsmt** [jisotalo/node-red-contrib-ads-client#22]
Question:

What if I have >200 individual variables and I want to subscribe to each one of them (preferably with individual settings for cycling time)?  Do I need to create 200 individual subscription nodes?  Or is there a possibility to use 1 node and subscribe to multiple variables (configured by the input msg for instance)  
Does anyone have the same scenario?  Suggestions on how to handle this efficiently?

**Comment by jisotalo** [comment]
Hi!

The ads-client libray handles one subscription for each variable, so yes you need one for each. Unless if there is some Node-RED method for making this easier.

In node.js it would be simple to call it for an array or so, but I don't know what is the best solution in Node-RED.

Could you perhaps create a STRUCT that contains all and subcribe with single fast-enough cycle time?

**Comment by vdwpsmt** [comment]
ok, thanks for the clarification.
The reason for asking is mainly because we are looking for a more performant way of communication between a beckhoff plc and the edge device.  So unfortunately grouping all in a single struct is not really a solution in that context.  (mix of low and high cycling rates needed).  
The Node-Red workaround could be something like "hiding" things in a subflow (with an array of variables as input), but that still doesn't make it very flexible to changing variablesets, cycling rates, differents machine configs etc...
Anyhow, first thing to check would be to monitor the performance of such a number of notifications.  Making this flexible in a multi-subscription node is only 2nd priority.   
Be interesting though to know if there's anyone else in need for this feature.

**Comment by jisotalo** [comment]
I see.

If possible, please use the ads-client (https://github.com/jisotalo/ads-client) directly in node.js and skip Node-RED so you can test these things easier.

However of course you could develop a node that supports multiple variables and subscribes them all.

**Comment by vdwpsmt** [comment]
ok, I'll consider both options.  
btw, impressively well documented this ads-client!  nice work!

**Comment by jisotalo** [comment]
Thanks! :)
