### ISSUE TITLE
Problem connecting to Beckhoff PLC 

### ISSUE THREAD

**Issue by Sulomus** [jisotalo/node-red-contrib-ads-client#24]
First of all I would like to thank you for this library! The examples and documentation is amazing!

Unfortunately I was not able to connect to my Beckhoff PLC. My task is to connect and take data from the PLC - I did not install it nor program it - so I don't know all the internal configuration etc. but I will try to explain our system as best as I can.

**What am I using?**
1) Beckhoff PLC 
- type: CP-4D57D0
- IP address: 172.21.9.60
- AmsNetID: 5.77.87.208.1.1 OR 158.196.119.70.3.1 (see why I say OR down below)
- ADS port: 851 OR 27907 (see why I say OR down below)

2) Linux PC with Node-RED 
- IP address: 172.21.9.50
- NodeRED verison: 3.0.2
- contrib-ads-client version: 1.4.0

**I enabled ADS and create symbols on the Beckhoff PLC as follow:**
![image](https://user-images.githubusercontent.com/49107150/208409661-55983139-7421-4102-a32e-f9b04ad84796.png)

**Why did I say AmsNET ID is 5.77.87.208.1.1 or 158.196.119.70.3.1?**
- I can see the AmsNET ID in two different places showing two different addresses.
- And I don't know which one is correct
- But I have tried both and both don't work.

One I can find here:
![Screenshot_14](https://user-images.githubusercontent.com/49107150/208425122-a4a02be8-abcc-42f4-8dc5-8ce47f0a4e9f.png)

And second one I can see here:
![Screenshot_8](https://user-images.githubusercontent.com/49107150/208425175-d06aa6d4-d252-44f0-8dc1-dc095357c01b.png)

**The same applies for the PORTS 851 OR 27907**
- again I can see two diffrent ports in two diffrent places.
Here:
![Screenshot_11](https://user-images.githubusercontent.com/49107150/208425285-96f6a417-6800-4df7-b7e5-4ca59b6f4fcb.png)

And here:
![Screenshot_12](https://user-images.githubusercontent.com/49107150/208425335-f363e5c9-18c4-42bf-b01c-2e9b31b09f58.png)

**This is the error I am getting:**
![Screenshot_9](https://user-images.githubusercontent.com/49107150/208426060-7f474f2f-c9f8-45b4-811e-dcf78b4d998f.png)

I do not understand why is it trying to connect to the local IP 127.0.0.1?
Shall I also configure something on my Linux PC?

I have tried every combination of AmsNetID and PORTS and none of the worked resulting in same error message (expect for the IP and PORT).

I will appreciate any help!
With regards,
Jakub Szlaur

**Comment by Sulomus** [comment]
+ Linux PC and Beckhoff PLC can see each other through ping command issued from the Linux PC:

![image](https://user-images.githubusercontent.com/49107150/208434262-2e522c7b-cb37-458a-8b4f-3d91d8ee0745.png)

**Comment by jisotalo** [comment]
Hello, thanks for the feedback!

The AmsNetId 5.77.xxx and port 851 are correct ones. The others would be if you wanted to connect directly to the I/O EtherCAT device.

As you are using raspberry pi without any TwinCAT router, you need to create the route manually. As default the library is trying to connect to local router which would pass the messages to the PLC (and that's how it done with router).

See the following:
https://github.com/jisotalo/ads-client/#setup-3---connecting-from-any-nodejs-supported-system-to-the-plc
https://github.com/jisotalo/ads-client/issues/51#issuecomment-758016428

**Comment by Sulomus** [comment]
> Hello, thanks for the feedback!
> 
> The AmsNetId 5.77.xxx and port 851 are correct ones. The others would be if you wanted to connect directly to the I/O EtherCAT device.
> 
> As you are using Linux PC without any TwinCAT router, you need to create the route manually. As default the library is trying to connect to local router which would pass the messages to the PLC (and that's how it done with router).
> 
> See the following: https://github.com/jisotalo/ads-client/#setup-3---connecting-from-any-nodejs-supported-system-to-the-plc [jisotalo/ads-client#51 (comment)](https://github.com/jisotalo/ads-client/issues/51#issuecomment-758016428)

Thank you very much! Will try ASAP.

**Comment by jisotalo** [comment]
I have a feeling that you have done something wrong with the route.

For example, when googling this error I found this comment
https://github.com/Beckhoff/ADS/issues/148#issuecomment-882391247

I have never created a route from XAE so I'm not sure if it's correct. Please try as in links I posted earlier.

**Comment by Sulomus** [comment]
Man you are amazing!
Managed to make it work without the unidirectional checked!

**Comment by jisotalo** [comment]
Awesome! Thanks for reporting that you got it working.
